force-app/main/default/objects/Clinical_Study__c/Clinical_Study__c.object-meta.xml
<CustomObject>
    <label>Clinical Study</label>
    <nameField>
        <displayFormat>CS-{000}</displayFormat>
        <label>Clinical Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Study_Participant__c.field-meta.xml
<CustomField>
    <fullName>Study_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Participant</label>
    <referenceTo>Study_Participant__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/Study_Participant__c.object-meta.xml
<CustomObject>
    <label>Study Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Study Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/fields/Clinical_Study__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Study</label>
    <referenceTo>Clinical_Study__c</referenceTo>
    <relationshipLabel>Study Participants (Clinical Study)</relationshipLabel>
    <relationshipName>Study_Participants1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>open</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/lightning-component-lesson/tests/classes/Test_StudyParticipantFilter.cls
/**
 * Created by Surkov Egor on 05.09.2019.
 */

@IsTest
private class Test_StudyParticipantFilter {
    @IsTest
    static void testBehavior() {
        Test.startTest();
        Contact contact = new Contact(LastName = 'TestFil');
        insert Contact;
        Clinical_Study__c clinicalStudy = new Clinical_Study__c(Title__c = 'MyTitleTest');
        insert clinicalStudy;

        Study_Participant__c studyParticipant = new Study_Participant__c(
                Contact__c = contact.Id,
                Clinical_Study__c = clinicalStudy.Id,
                Status__c = 'Open'
        );

        insert studyParticipant;

        StudyParticipantFilter filter = new StudyParticipantFilter();
        filter.status = 'Open';
        filter.studyTitleTerm = 'Title';

        PaginationData paginationData = new PaginationData();
        SearchResponse response = SearchService.search(filter, paginationData);

        Test.stopTest();

        System.assert(response.paginationData.currentPageCount == 1, 'wrong records count per count page');
        System.assert(response.pageRecords.size() == 1, 'wrong records count per count page');
    }
}